### ISSUE TITLE
Retain the cursor position after highlighting

### ISSUE THREAD

**Issue by geongeorge** [geongeorge/i-hate-regex#10]
**Feature Request**

The cursor inside the matches box jumps to the initial position after a person edits and highlighting is performed.
I was not able to find a proper method to get the cursor location inside a div and place the cursor at that position after I add the highlighting HTML.

<img src="https://user-images.githubusercontent.com/29296982/73593538-680fd600-452b-11ea-9912-9ffa190c3560.png" width=400>

This also makes it so that we cannot perform real-time highlighting. I've set a timeout:
`components/post-components/MatchBox.vue`

```js

matchboxChanged(event) {
      var node = this.$refs.matchbox;
      // console.log(typeTimeout);
      if (typeTimeout) {
        clearTimeout(typeTimeout);
      }
      typeTimeout = setTimeout(() => {
        this.boxEdited();
      }, 2000);
    }

```

**Comment by guywarburg** [comment]
After reading a bit online this seems to be a bit harder than I initially thought...

The naive approach would be to debounce / wait for an unfocus event and then update the highlights, though that isn't the best user-experience.

Another approach I found [here](https://codersblock.com/blog/highlight-text-inside-a-textarea/) is to have a div behind the textarea. Duplicate all changes to the div and then process the div while the user can freely edit the textarea. As explained there are some edge cases to consider such as scrolling, but seems to work. From what I could see on [Regex101](https://regex101.com/) it seems that they do something similar but with a canvas instead of a div.

The other solution I found is this [SO answer](https://stackoverflow.com/questions/4811822/get-a-ranges-start-and-end-offsets-relative-to-its-parent-container/4812022#4812022) which provides a snippet to get the caret offset which you could later set.

Hope this helps :)

**Comment by geongeorge** [comment]
Thank you for checking it out 😄 

I have tried the caret position snippet. I do not remember getting a good result with it.
I'll try it again But I think even if it were gonna work, it's gonna be a dirty hack because we'll need to add the characters for all the highlighting and the divs are gonna mess this up.

I'll try to go with [this](https://codersblock.com/blog/highlight-text-inside-a-textarea/) and see how it goes

**Comment by geongeorge** [comment]
Thanks @guywarburg
